import { QuizQuestion } from './types';

// Helper function to shuffle an array
const shuffleArray = <T,>(array: T[]): T[] => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

const allQuestions: Record<number, QuizQuestion[]> = {
  1: [
    { question: "O que é crise de identidade espiritual?", options: ["É perder a fé em momentos difíceis.", "É não saber quem se é aos olhos de Deus, buscando valor em coisas do mundo.", "É deixar de frequentar a igreja.", "É ter muitas dúvidas sobre o futuro."], correctAnswerIndex: 1, explanation: "Referência: 1 João 3:1-2 – “Agora somos filhos de Deus... o mundo não nos conhece, porque não o conhece a Ele.\"" },
    { question: "Por que muitos jovens se sentem perdidos?", options: ["Porque não têm amigos verdadeiros.", "Porque não conhecem sua verdadeira identidade em Cristo.", "Porque não estudam o suficiente.", "Porque não seguem modas e tendências."], correctAnswerIndex: 1, explanation: "Referência: João 1:12 – “A todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus.\"" },
    { question: "Como o mundo influencia a forma como o jovem se vê?", options: ["Incentivando o amor próprio saudável.", "Mostrando que todos são iguais.", "Definindo valor por aparência, popularidade e sucesso.", "Ensinando a valorizar a espiritualidade."], correctAnswerIndex: 2, explanation: "Referência: 1 João 2:15-17 – “Não ameis o mundo, nem o que no mundo há...”" },
    { question: "Quem define o valor do ser humano segundo a Bíblia?", options: ["A sociedade.", "Os próprios sentimentos.", "Deus, o Criador.", "As opiniões das pessoas."], correctAnswerIndex: 2, explanation: "Referência: Gênesis 1:26 – “Façamos o homem à nossa imagem, conforme a nossa semelhança.\"" },
    { question: "O que acontece quando um jovem busca aceitação nas redes sociais?", options: ["Ele fortalece sua fé.", "Ele descobre sua vocação.", "Ele corre o risco de basear seu valor em curtidas e aprovação humana.", "Ele cresce espiritualmente."], correctAnswerIndex: 2, explanation: "Referência: Romanos 12:2 – “Não vos conformeis com este mundo, mas transformai-vos pela renovação da mente.\"" },
    { question: "Como Deus vê os jovens mesmo em meio às crises?", options: ["Como pessoas fracas e confusas.", "Como filhos amados e preciosos.", "Como pecadores sem esperança.", "Como pessoas que precisam provar seu valor."], correctAnswerIndex: 1, explanation: "Referência: Isaías 43:4 – “Visto que foste precioso aos meus olhos... eu te amei.”" },
    { question: "Quais fatores geram confusão de identidade na adolescência?", options: ["O excesso de tempo livre.", "As mudanças hormonais.", "As comparações, a busca por aprovação e as mentiras do mundo.", "A falta de conhecimento científico."], correctAnswerIndex: 2, explanation: "Referência: Jeremias 17:9 – “Enganoso é o coração, mais do que todas as coisas...\"" },
    { question: "Como a identidade espiritual afeta todas as áreas da vida?", options: ["Influencia apenas a vida religiosa.", "Afeta a forma como pensamos, agimos e nos relacionamos.", "Não tem relação com a vida social.", "Só é importante na igreja."], correctAnswerIndex: 1, explanation: "Referência: Efésios 2:10 – “Pois somos feitura sua, criados em Cristo Jesus para boas obras...\"" },
    { question: "Qual é o perigo de se comparar com os outros?", options: ["Pode gerar admiração e aprendizado.", "Faz crescer espiritualmente.", "Gera inveja, insegurança e afastamento do propósito de Deus.", "Ajuda a desenvolver disciplina."], correctAnswerIndex: 2, explanation: "Referência: Gálatas 6:4 – “Cada um examine o seu próprio trabalho... e não se glorie em outro.\"" },
    { question: "O que a sociedade tenta impor sobre a identidade dos adolescentes?", options: ["Que são filhos de Deus e únicos.", "Que devem viver segundo os padrões do Reino.", "Que o valor depende da aparência, fama e sucesso.", "Que devem buscar santidade acima de tudo."], correctAnswerIndex: 2, explanation: "Referência: 1 Samuel 16:7 – “O Senhor não vê como vê o homem... o homem vê o exterior, porém o Senhor olha o coração.”" },
    { question: "De acordo com Gênesis 1, à imagem de quem fomos criados?", options: ["Anjos", "Natureza", "Deus", "Estrelas"], correctAnswerIndex: 2, explanation: "Gênesis 1:27 afirma claramente: 'Deus criou o homem à sua imagem; à imagem de Deus o criou'. Isso nos dá valor e dignidade intrínsecos." },
    { question: "O que significa ser criado à imagem de Deus?", options: ["Ter superpoderes", "Refletir Seu caráter e amor", "Ser fisicamente igual a Ele", "Nunca cometer erros"], correctAnswerIndex: 1, explanation: "Ser imagem de Deus não é sobre aparência física, mas sobre refletir Seus atributos morais, espirituais e intelectuais, como amor, justiça e criatividade. (Efésios 5:1)" },
    { question: "A criação do homem foi um ato...", options: ["Acidental", "Intencional e planejado", "Sem propósito", "Rápido e sem detalhes"], correctAnswerIndex: 1, explanation: "A narrativa da criação em Gênesis mostra Deus agindo com propósito e planejamento, culminando na criação da humanidade como o ápice de Sua obra. (Gênesis 1:26)" },
    { question: "Ser imagem de Deus nos dá...", options: ["Uma licença para pecar", "Responsabilidades", "Tristeza", "Imunidade a problemas"], correctAnswerIndex: 1, explanation: "Como portadores da imagem de Deus, temos a responsabilidade de cuidar da criação e de representar Seu caráter no mundo. (Gênesis 1:28)" },
    { question: "Qual atributo de Deus é refletido em nossa capacidade de criar (arte, música, etc)?", options: ["Sua justiça", "Sua criatividade", "Sua ira", "Sua santidade"], correctAnswerIndex: 1, explanation: "Como fomos feitos à imagem de um Deus criativo, também recebemos a capacidade de criar, inovar e apreciar a beleza. (Êxodo 35:31-33)" },
  ],
  2: [
    { question: "Qual é a base para nossa dignidade como seres humanos?", options: ["As conquistas e talentos que possuímos.", "A opinião das pessoas ao nosso redor.", "O fato de sermos criados à imagem e semelhança de Deus.", "A posição social e o sucesso que alcançamos."], correctAnswerIndex: 2, explanation: "Referência: Gênesis 1:26 – “Façamos o homem à nossa imagem, conforme a nossa semelhança.\"" },
    { question: "Por que fomos criados de forma única por Deus?", options: ["Para competir com os outros.", "Para cumprir um propósito específico e refletir o Criador.", "Para sermos independentes d'Ele.", "Para buscarmos reconhecimento humano."], correctAnswerIndex: 1, explanation: "Referência: Salmos 139:13-14 – “De um modo assombrosamente maravilhoso fui formado...\"" },
    { question: "Qual é a relação entre identidade e propósito segundo a Bíblia?", options: ["Quem descobre sua identidade em Cristo entende o propósito para o qual foi criado.", "São conceitos totalmente diferentes.", "O propósito é mais importante que a identidade.", "A identidade vem depois de cumprir o propósito."], correctAnswerIndex: 0, explanation: "Referência: Efésios 2:10 – “Pois somos feitura sua, criados em Cristo Jesus para boas obras...\"" },
    { question: "O que o Salmo 139:14 nos ensina?", options: ["Que devemos buscar perfeição física.", "Que Deus se alegra apenas com os mais fortes.", "Que fomos criados de modo maravilhoso e intencional.", "Que a vida humana é fruto do acaso."], correctAnswerIndex: 2, explanation: "Referência: Salmos 139:14 – “Eu te louvarei, porque de um modo assombrosamente maravilhoso fui formado...\"" },
    { question: "Como a criação revela o cuidado de Deus por cada pessoa?", options: ["Mostrando que todos são iguais e sem valor individual.", "Mostrando que Deus conhece e planejou cada detalhe da nossa existência.", "Mostrando que a natureza é mais importante que o homem.", "Mostrando que o homem é resultado da evolução."], correctAnswerIndex: 1, explanation: "Referência: Salmos 139:15-16 – “Os teus olhos viram o meu corpo ainda informe... todas estas coisas foram escritas no teu livro.\"" },
    { question: "Por que cada ser humano tem valor inegociável?", options: ["Porque possui habilidades especiais.", "Porque é amado e criado à imagem de Deus.", "Porque tem livre-arbítrio.", "Porque pode conquistar qualquer coisa que desejar."], correctAnswerIndex: 1, explanation: "Referência: Isaías 43:4 – “Visto que foste precioso aos meus olhos... eu te amei.”" },
    { question: "Como a imagem de Deus em nós reflete nossa identidade?", options: ["Mostrando que podemos dominar os outros.", "Revelando que fomos feitos para refletir o caráter, o amor e a santidade de Deus.", "Mostrando que somos deuses na Terra.", "Indicando que podemos viver como quisermos."], correctAnswerIndex: 1, explanation: "Referência: Efésios 4:24 – “E vos revistais do novo homem, criado segundo Deus em verdadeira justiça e santidade.\"" },
    { question: "Qual é o impacto de reconhecer que Deus nos formou?", options: ["Gera orgulho e independência.", "Produz humildade, gratidão e propósito.", "Faz-nos achar que somos perfeitos.", "Enfraquece nossa autoconfiança."], correctAnswerIndex: 1, explanation: "Referência: Jeremias 1:5 – “Antes que te formasse no ventre, te conheci.”" },
    { question: "Como a verdade da criação pode combater a baixa autoestima?", options: ["Fazendo-nos focar em nós mesmos.", "Lembrando que fomos criados por um Deus amoroso e intencional.", "Fazendo-nos comparar com os outros.", "Mostrando que temos que provar nosso valor."], correctAnswerIndex: 1, explanation: "Referência: Efésios 1:4 – “Nos elegeu nele antes da fundação do mundo...\"" },
    { question: "Qual é o resultado de ignorar que fomos criados por Deus?", options: ["Encontramos paz interior.", "Caímos em confusão e tentamos definir nosso próprio valor sem direção.", "Ficamos mais sábios e autônomos.", "Aprendemos a amar mais as pessoas."], correctAnswerIndex: 1, explanation: "Referência: Romanos 1:21 – “Conhecendo a Deus, não o glorificaram como Deus... e o seu coração insensato se obscureceu.\"" },
    { question: "O que o pecado causou na relação do homem com Deus?", options: ["Aproximação", "Indiferença", "Separação", "Fortalecimento"], correctAnswerIndex: 2, explanation: "O pecado criou uma barreira espiritual entre a humanidade e um Deus santo, resultando em separação. (Isaías 59:2)" },
    { question: "Romanos 3:23 afirma que 'todos...'", options: ["São perfeitos", "Pecaram", "São anjos", "Não precisam de Deus"], correctAnswerIndex: 1, explanation: "Este versículo é fundamental para entender que a condição de pecador é universal, afetando toda a humanidade. Ninguém está isento. (Romanos 3:23)" },
    { question: "Após a queda, o homem começou a sentir...", options: ["Paz e alegria", "Apenas amor", "Medo e vergonha", "Orgulho e superioridade"], correctAnswerIndex: 2, explanation: "A primeira reação de Adão e Eva após pecarem foi se esconderem de Deus, sentindo medo e vergonha de sua nudez. (Gênesis 3:10)" },
    { question: "Apesar da queda, Deus...", options: ["Abandonou a humanidade", "Desistiu de seu plano", "Prometeu um Redentor", "Castigou sem esperança"], correctAnswerIndex: 2, explanation: "Imediatamente após a queda, Deus prometeu um Salvador que esmagaria a cabeça da serpente, mostrando que Ele não havia desistido da humanidade. (Gênesis 3:15)" },
    { question: "O que o 'salário do pecado' resulta, segundo Romanos 6:23?", options: ["Riqueza", "Fama", "Morte", "Sabedoria"], correctAnswerIndex: 2, explanation: "Romanos 6:23 é claro: 'Pois o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor'. A morte aqui significa separação eterna de Deus." },
  ],
  3: [
    { question: "O que o pecado causou na identidade humana?", options: ["Trouxe liberdade e clareza espiritual.", "Fortaleceu o relacionamento com Deus.", "Distorceu a imagem de Deus em nós, gerando culpa e afastamento.", "Aperfeiçoou nossa natureza humana."], correctAnswerIndex: 2, explanation: "Referência: Romanos 5:12 – “Por um só homem entrou o pecado no mundo, e pelo pecado a morte...\"" },
    { question: "Como as máscaras espirituais afetam nossa comunhão com Deus?", options: ["Aproximam-nos d'Ele através da aparência de santidade.", "Afastam-nos de Deus, pois escondem quem realmente somos.", "Tornam-nos mais aceitos pela sociedade cristã.", "Ajudam-nos a lidar melhor com as críticas."], correctAnswerIndex: 1, explanation: "Referência: Gênesis 3:8 – “E esconderam-se Adão e sua mulher da presença do Senhor Deus...\"" },
    { question: "Qual é a relação entre culpa e afastamento de Deus?", options: ["A culpa aproxima as pessoas de Deus.", "A culpa saudável é sinal de maturidade espiritual.", "A culpa não confessada nos afasta da presença do Pai.", "A culpa não tem relação com a vida espiritual."], correctAnswerIndex: 2, explanation: "Referência: Salmos 32:3-5 – “Enquanto calei os meus pecados, envelheceram os meus ossos... confessei-te o meu pecado.\"" },
    { question: "Como a vergonha molda o comportamento do ser humano?", options: ["Leva à humildade e arrependimento.", "Gera fuga, medo e desejo de esconder as falhas.", "Motiva o crescimento espiritual.", "Ensina a depender de Deus naturalmente."], correctAnswerIndex: 1, explanation: "Referência: Gênesis 3:10 – “Tive medo, porque estava nu, e escondi-me.\"" },
    { question: "Por que as máscaras não sustentam uma identidade firme?", options: ["Porque são necessárias apenas em público.", "Porque escondem a verdade e nos impedem de viver como filhos de Deus.", "Porque a sociedade as reprova.", "Porque Deus não as percebe."], correctAnswerIndex: 1, explanation: "Referência: 1 Samuel 16:7 – “O Senhor não vê como o homem vê; o homem olha para o exterior, porém o Senhor olha para o coração.\"" },
    { question: "Qual é a primeira reação do homem ao errar na Bíblia?", options: ["Procurar ajuda imediatamente.", "Reconhecer o erro diante de Deus.", "Esconder-se e justificar suas ações.", "Permanecer em oração e arrependimento."], correctAnswerIndex: 2, explanation: "Referência: Gênesis 3:12 – “A mulher que me deste por companheira, ela me deu da árvore, e comi.\"" },
    { question: "Como a misericórdia de Deus se revela mesmo após o pecado?", options: ["Através da condenação do pecador.", "Pela punição justa e sem perdão.", "Pelo perdão e pela promessa de restauração em Cristo.", "Negando o erro e ignorando o pecado."], correctAnswerIndex: 2, explanation: "Referência: Gênesis 3:21 – “E fez o Senhor Deus túnicas de peles para Adão e sua mulher, e os vestiu.\"" },
    { question: "O que impede as pessoas de se enxergarem como Deus vê?", options: ["A falta de oportunidades na vida.", "As mentiras do mundo e o engano do coração.", "O excesso de conhecimento bíblico.", "A comparação com Jesus."], correctAnswerIndex: 1, explanation: "Referência: Jeremias 17:9 – “Enganoso é o coração, mais do que todas as coisas, e perverso.\"" },
    { question: "Quais mentiras o diabo planta sobre quem somos?", options: ["Que somos amados e escolhidos.", "Que não temos valor, propósito ou perdão.", "Que somos perfeitos em Cristo.", "Que Deus nos usa poderosamente."], correctAnswerIndex: 1, explanation: "Referência: João 8:44 – “Quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso e pai da mentira.\"" },
    { question: "Qual é a saída bíblica para a crise gerada pelo pecado?", options: ["Negar o erro e seguir em frente.", "Buscar autoajuda e meditação.", "Arrependimento e fé na redenção de Cristo.", "Esforçar-se para ser melhor sem Deus."], correctAnswerIndex: 2, explanation: "Referência: 1 João 1:9 – “Se confessarmos os nossos pecados, Ele é fiel e justo para nos perdoar e nos purificar de toda injustiça.”" },
    { question: "Segundo 2 Coríntios 5:17, quem está em Cristo é...", options: ["A mesma pessoa", "Um pouco melhorado", "Nova criação", "Alguém sem memória"], correctAnswerIndex: 2, explanation: "A transformação em Cristo é radical. Não é uma reforma, mas uma recriação completa do nosso espírito. (2 Coríntios 5:17)" },
    { question: "Quem realiza essa transformação para 'nova criação'?", options: ["Nós mesmos, com esforço", "O Espírito Santo", "Nossos amigos", "O pastor da igreja"], correctAnswerIndex: 1, explanation: "O novo nascimento é uma obra sobrenatural do Espírito Santo em nós no momento em que cremos em Jesus. (Tito 3:5)" },
    { question: "Essa nova identidade é baseada em...", options: ["Nossas obras", "Nossa família", "Nossa fé em Cristo", "Nossa popularidade"], correctAnswerIndex: 2, explanation: "Nossa identidade não vem do que fazemos, mas do que Cristo fez por nós. Ela é recebida pela fé. (Gálatas 2:20)" },
    { question: "A nossa mente também é renovada neste processo?", options: ["Não, ela permanece a mesma", "Sim, pela Palavra de Deus", "Apenas se fizermos terapia", "Não é importante"], correctAnswerIndex: 1, explanation: "Romanos 12:2 nos exorta a sermos transformados pela 'renovação da nossa mente', o que acontece quando meditamos e aplicamos a Palavra de Deus em nossa vida." },
    { question: "De acordo com João 1:12, o que ocorre quando uma pessoa crê em Jesus?", options: ["Torna-se anjo", "Torna-se membro de igreja", "Torna-se filho de Deus", "Torna-se mais inteligente"], correctAnswerIndex: 2, explanation: "João 1:12 afirma que, ao crer em Jesus, recebemos o direito de nos tornarmos filhos de Deus, uma nova identidade espiritual." },
  ],
  4: [
    { question: "O que significa ser adotado por Deus?", options: ["Ser apenas uma criatura d'Ele.", "Ser aceito em uma religião.", "Tornar-se parte da família de Deus por meio de Jesus Cristo.", "Seguir boas obras para merecer salvação."], correctAnswerIndex: 2, explanation: "Referência: João 1:12 – “A todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus.\"" },
    { question: "Qual é o efeito da cruz na nossa identidade?", options: ["Revelar que somos incapazes de mudar.", "Mostrar o quanto o pecado é grave.", "Restaurar nossa verdadeira identidade como filhos redimidos.", "Ensinar-nos a depender apenas de nós mesmos."], correctAnswerIndex: 2, explanation: "Referência: Gálatas 2:20 – “Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim.\"" },
    { question: "Como a graça redefine quem somos?", options: ["Tira nossa responsabilidade sobre as ações.", "Nos liberta da culpa e nos faz viver como filhos amados, não como escravos.", "Faz-nos superiores aos outros.", "Ensina que podemos viver sem arrependimento."], correctAnswerIndex: 1, explanation: "Referência: Efésios 2:8-9 – “Porque pela graça sois salvos, por meio da fé... não vem das obras.\"" },
    { question: "O que nos torna participantes da família de Deus?", options: ["As boas ações e a frequência na igreja.", "A fé em Jesus Cristo e a adoção espiritual.", "O batismo nas águas.", "O conhecimento das Escrituras."], correctAnswerIndex: 1, explanation: "Referência: Romanos 8:15-17 – “Recebestes o espírito de adoção, pelo qual clamamos: Aba, Pai.\"" },
    { question: "Por que nossa identidade não depende de obras?", options: ["Porque ninguém consegue fazer boas obras o tempo todo.", "Porque as obras são inúteis.", "Porque ela é um presente da graça de Deus, não uma recompensa por mérito.", "Porque a fé elimina qualquer ação."], correctAnswerIndex: 2, explanation: "Referência: Efésios 2:9 – “Não vem das obras, para que ninguém se glorie.\"" },
    { question: "Como o sangue de Jesus nos transforma?", options: ["Limpando nossos pecados e nos dando uma nova identidade em Cristo.", "Apenas servindo como símbolo religioso.", "Tornando-nos perfeitos humanamente.", "Fazendo-nos esquecer o passado sem arrependimento."], correctAnswerIndex: 0, explanation: "Referência: 1 João 1:7 – “O sangue de Jesus Cristo, seu Filho, nos purifica de todo o pecado.\"" },
    { question: "O que nos separava de Deus antes de Cristo?", options: ["A ignorância espiritual.", "A falta de conhecimento bíblico.", "O pecado e a desobediência.", "A ausência de boas obras."], correctAnswerIndex: 2, explanation: "Referência: Isaías 59:2 – “As vossas iniquidades fazem separação entre vós e o vosso Deus.\"" },
    { question: "Qual é a diferença entre religião e nova identidade?", options: ["A religião é tradição humana; a nova identidade é relacionamento com Deus por meio de Cristo.", "A religião garante salvação; a identidade não.", "A identidade é apenas um sentimento.", "Ambas são iguais, apenas com nomes diferentes."], correctAnswerIndex: 0, explanation: "Referência: 2 Coríntios 5:17 – “Se alguém está em Cristo, nova criatura é; as coisas velhas já passaram.”" },
    { question: "Como a fé nos reposiciona diante de Deus?", options: ["Faz-nos sentir melhores que os outros.", "Leva-nos a conquistar bênçãos materiais.", "Muda nosso status de pecadores condenados para filhos justificados.", "Ensina-nos a seguir rituais religiosos."], correctAnswerIndex: 2, explanation: "Referência: Romanos 5:1 – “Sendo, pois, justificados pela fé, temos paz com Deus por nosso Senhor Jesus Cristo.”" },
    { question: "O que 1 Pedro 2:9 declara sobre nós?", options: ["Que somos indignos do amor de Deus.", "Que somos apenas pecadores perdoados.", "Que somos geração eleita, sacerdócio real e povo adquirido para anunciar as virtudes de Deus.", "Que devemos viver escondidos do mundo."], correctAnswerIndex: 2, explanation: "Referência: 1 Pedro 2:9 – “Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido...”" },
    { question: "Em Cristo, qual é a nossa nova posição?", options: ["Servos distantes", "Inimigos", "Filhos de Deus", "Conhecidos"], correctAnswerIndex: 2, explanation: "Através da fé em Jesus, somos adotados na família de Deus e nos tornamos Seus filhos. (Gálatas 4:4-5)" },
    { question: "Essa filiação é resultado do quê?", options: ["Do nosso esforço", "Do grande amor de Deus", "Do acaso", "De uma compra"], correctAnswerIndex: 1, explanation: "Nossa adoção como filhos não é por nosso mérito, mas um ato do imenso amor e da soberana vontade de Deus. (Efésios 1:5)" },
    { question: "Ser filho de Deus significa que somos...", options: ["Co-herdeiros com Cristo", "Mais importantes que os anjos", "Imunes ao sofrimento", "Perfeitos"], correctAnswerIndex: 0, explanation: "Como filhos de Deus, compartilhamos da herança de Cristo. Tudo o que pertence a Ele, por direito, também nos é prometido. (Romanos 8:17)" },
    { question: "Se somos filhos, então somos herdeiros de Deus. O que herdaremos?", options: ["Problemas", "Riquezas terrenas", "A vida eterna e as promessas de Deus", "Nada"], correctAnswerIndex: 2, explanation: "Nossa herança como filhos de Deus inclui a vida eterna, um relacionamento restaurado com Ele e todas as bênçãos espirituais prometidas em Cristo. (Efésios 1:3)" },
    { question: "Como podemos viver como filhos amados no dia a dia?", options: ["Fazendo tudo o que queremos", "Ignorando as outras pessoas", "Obedecendo a Deus por amor, não por medo", "Tentando comprar o favor de Deus"], correctAnswerIndex: 2, explanation: "A resposta de um filho amado não é a rebeldia, mas uma obediência que brota da gratidão e do amor, confiando que os caminhos do Pai são os melhores. (1 João 5:3)" },
  ],
  5: [
    { question: "O que é viver coerentemente com a fé cristã?", options: ["Ir à igreja apenas aos domingos.", "Viver de acordo com a Palavra de Deus em todas as áreas da vida.", "Mostrar-se espiritual diante dos outros.", "Evitar qualquer tipo de problema."], correctAnswerIndex: 1, explanation: "Referência: Tiago 1:22 – “Sede cumpridores da palavra, e não somente ouvintes, enganando-vos a vós mesmos.\"" },
    { question: "Como se expressa a identidade cristã no cotidiano?", options: ["Apenas através de palavras religiosas.", "Por meio de atitudes, escolhas e amor que refletem Cristo.", "Pela quantidade de versículos decorados.", "Pelo modo de se vestir."], correctAnswerIndex: 1, explanation: "Referência: Mateus 5:16 – “Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem a vosso Pai.”" },
    { question: "Por que a obediência é sinal de identidade transformada?", options: ["Porque quem obedece quer ser aceito pela sociedade.", "Porque obediência demonstra submissão cega.", "Porque quem ama a Deus deseja viver segundo Sua vontade.", "Porque garante bênçãos materiais."], correctAnswerIndex: 2, explanation: "Referência: João 14:15 – “Se me amais, guardareis os meus mandamentos.”" },
    { question: "Como a cultura tenta apagar a identidade cristã?", options: ["Incentivando os jovens a seguir princípios bíblicos.", "Promovendo valores contrários à Palavra de Deus e exaltando o ego.", "Reforçando a importância da fé.", "Ensinando respeito às diferenças."], correctAnswerIndex: 1, explanation: "Referência: Romanos 12:2 – “Não vos conformeis com este mundo, mas transformai-vos pela renovação da vossa mente.\"" },
    { question: "O que é santidade prática na vida diária?", options: ["Viver sem cometer erros.", "Separar-se do pecado e buscar agradar a Deus nas atitudes diárias.", "Afastar-se completamente das pessoas.", "Evitar responsabilidades."], correctAnswerIndex: 1, explanation: "Referência: 1 Pedro 1:15-16 – “Sede santos em todo o vosso procedimento.”" },
    { question: "Qual é o testemunho mais poderoso de identidade cristã?", options: ["Palavras bonitas e pregações longas.", "Uma vida que reflete o caráter de Cristo com amor e integridade.", "Realizar grandes milagres.", "Ser conhecido por muitos na igreja."], correctAnswerIndex: 1, explanation: "Referência: Gálatas 2:20 – “Já não sou eu quem vive, mas Cristo vive em mim.”" },
    { question: "Como aplicar a Bíblia em decisões diárias?", options: ["Consultando apenas quando surgem crises.", "Deixando que os sentimentos decidam.", "Usando os princípios da Palavra como base para cada escolha.", "Seguindo o que os outros fazem."], correctAnswerIndex: 2, explanation: "Referência: Salmos 119:105 – “Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho.\"" },
    { question: "Por que a renovação da mente é contínua?", options: ["Porque o mundo constantemente tenta moldar nossos pensamentos.", "Porque o cristão nunca é perdoado totalmente.", "Porque a salvação depende disso.", "Porque precisamos agradar a todos."], correctAnswerIndex: 0, explanation: "Referência: Romanos 12:2 – “Transformai-vos pela renovação da vossa mente.”" },
    { question: "Como ser um reflexo de Cristo na escola ou trabalho?", options: ["Agindo com honestidade, amor e excelência em tudo o que faz.", "Falando sobre religião o tempo todo.", "Ignorando as pessoas diferentes.", "Criticando quem não é cristão."], correctAnswerIndex: 0, explanation: "Referência: Colossenses 3:23 – “Tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor, e não aos homens.\"" },
    { question: "Como enfrentar críticas sem perder a identidade em Cristo?", options: ["Retalhando com palavras duras.", "Lembrando-se de quem é em Deus e reagindo com mansidão.", "Tentando se justificar diante de todos.", "Abandonando sua fé para ser aceito."], correctAnswerIndex: 1, explanation: "Referência: Mateus 5:11-12 – “Bem-aventurados sois vós quando vos injuriarem... regozijai-vos, porque é grande o vosso galardão nos céus.”" },
    { question: "Para quem 'não há condenação'?", options: ["Para todos, sem exceção", "Para os que são perfeitos", "Para os que estão em Cristo Jesus", "Para ninguém"], correctAnswerIndex: 2, explanation: "Romanos 8:1 especifica que a ausência de condenação é para aqueles que estão unidos a Cristo pela fé." },
    { question: "Se confessarmos os nossos pecados, Ele é fiel e justo para...", options: ["Nos punir severamente", "Nos perdoar e purificar", "Nos lembrar deles sempre", "Contar para todos"], correctAnswerIndex: 1, explanation: "A promessa de Deus é que a confissão sincera leva ao perdão completo e à purificação de toda injustiça. (1 João 1:9)" },
    { question: "A liberdade em Cristo nos dá o direito de...", options: ["Continuar pecando", "Viver para agradar a Deus", "Julgar os outros", "Fazer o que quisermos sem consequências"], correctAnswerIndex: 1, explanation: "Fomos libertados do pecado não para voltarmos a ele, mas para vivermos em novidade de vida, servindo a Deus. (Gálatas 5:13)" },
    { question: "O que o sangue de Jesus faz por nós?", options: ["Nos torna ricos", "Nos purifica de todo pecado", "Nos dá força física", "Nos torna famosos"], correctAnswerIndex: 1, explanation: "1 João 1:7 diz que 'o sangue de Jesus, seu Filho, nos purifica de todo pecado'. É o fundamento do nosso perdão e liberdade." },
    { question: "Quem pagou o preço pela nossa liberdade?", options: ["Nós mesmos, com boas obras", "Nossos pais", "Jesus Cristo, na cruz", "Ninguém pagou"], correctAnswerIndex: 2, explanation: "Fomos 'comprados por um bom preço'. O sacrifício de Cristo foi o pagamento que quitou a dívida do nosso pecado, nos libertando da escravidão. (1 Coríntios 6:20)" },
  ],
  6: [
    { question: "O que o espelho da Palavra revela sobre nós?", options: ["Nossas falhas e também quem somos em Cristo.", "Apenas nossos pecados.", "Que somos incapazes de mudar.", "Que precisamos nos comparar com os outros."], correctAnswerIndex: 0, explanation: "Referência: Tiago 1:23-25 – “Aquele que atenta bem para a lei perfeita da liberdade... será bem-aventurado no seu feito.\"" },
    { question: "Por que a Bíblia é mais confiável que nossos sentimentos?", options: ["Porque os sentimentos mudam, mas a Palavra de Deus permanece para sempre.", "Porque a Bíblia é apenas um livro antigo.", "Porque sentimentos são sempre ruins.", "Porque fé e emoção são a mesma coisa."], correctAnswerIndex: 0, explanation: "Referência: Jeremias 17:9 – “Enganoso é o coração, mais do que todas as coisas, e perverso; quem o conhecerá?”" },
    { question: "O que acontece quando deixamos de ouvir a Palavra?", options: ["Ficamos mais independentes espiritualmente.", "Fortalecemos nossa fé pessoal.", "Perdemos direção, discernimento e clareza sobre quem somos.", "Nos tornamos mais maduros."], correctAnswerIndex: 2, explanation: "Referência: Salmos 119:9 – “De que maneira o jovem purificará o seu caminho? Observando-o conforme a tua palavra.”" },
    { question: "Qual é o resultado de se olhar continuamente na Bíblia?", options: ["Conhecer a verdade e ser transformado por ela.", "Ter mais informações religiosas.", "Aprender a julgar os outros.", "Ficar dependente de líderes espirituais."], correctAnswerIndex: 0, explanation: "Referência: João 8:31-32 – “Se vós permanecerdes na minha palavra... conhecereis a verdade, e a verdade vos libertará.\"" },
    { question: "Como a verdade nos liberta da confusão sobre quem somos?", options: ["Fazendo-nos ignorar as opiniões alheias.", "Mostrando que nossa identidade está em Cristo, não no mundo.", "Tornando-nos perfeitos aos olhos dos outros.", "Fazendo-nos superiores espiritualmente."], correctAnswerIndex: 1, explanation: "Referência: João 17:17 – “Santifica-os na verdade; a tua palavra é a verdade.\"" },
    { question: "Qual é a função do Espírito Santo nesse processo?", options: ["Apenas consolar nos momentos difíceis.", "Ensinar, lembrar e confirmar quem somos em Deus.", "Mostrar os erros dos outros.", "Nos afastar do mundo completamente."], correctAnswerIndex: 1, explanation: "Referência: João 14:26 – “Mas o Consolador, o Espírito Santo... vos ensinará todas as coisas e vos fará lembrar de tudo quanto vos tenho dito.\"" },
    { question: "Por que precisamos decidir por viver a identidade de Deus?", options: ["Porque é uma escolha diária de fé e obediência à Palavra.", "Porque Deus obriga todos a segui-Lo.", "Porque isso nos faz melhores que os outros.", "Porque a identidade em Cristo é automática."], correctAnswerIndex: 0, explanation: "Referência: Josué 24:15 – “Escolhei hoje a quem sirvais... porém eu e a minha casa serviremos ao Senhor.\"" },
    { question: "O que significa não esquecer quem somos após o estudo?", options: ["Aplicar a Palavra e viver de modo coerente com a verdade aprendida.", "Apenas lembrar dos versículos decorados.", "Ensinar aos outros sem praticar.", "Esquecer o passado completamente."], correctAnswerIndex: 0, explanation: "Referência: Tiago 1:25 – “Aquele que atenta bem para a lei perfeita... e persevera nela... será bem-aventurado.\"" },
    { question: "Como manter viva a identidade revelada na jornada?", options: ["Continuando a meditar na Palavra, orar e andar em comunhão com Deus.", "Buscando aprovação dos outros.", "Seguindo apenas tradições religiosas.", "Afastando-se do mundo completamente."], correctAnswerIndex: 0, explanation: "Referência: Colossenses 3:16 – “A palavra de Cristo habite em vós ricamente... ensinando e aconselhando-vos uns aos outros.\"" },
    { question: "Por que olhar para o espelho certo muda tudo?", options: ["Porque ao ver-se pela Palavra, o cristão descobre seu valor e propósito em Deus.", "Porque o espelho mostra nossos defeitos físicos.", "Porque ensina a competir com os outros.", "Porque reflete nossa aparência espiritual."], correctAnswerIndex: 0, explanation: "Referência: 1 Samuel 16:7 – “O Senhor não vê como vê o homem; o homem olha para o exterior, porém o Senhor olha para o coração.\"" },
    { question: "Em Efésios 2:10, somos chamados de...", options: ["'Acidentes cósmicos'", "'Feitura de Deus'", "'Seres sem importância'", "'Projeto inacabado'"], correctAnswerIndex: 1, explanation: "A palavra grega para 'feitura' é 'poiema', de onde vem 'poema'. Somos a obra-prima, o poema de Deus. (Efésios 2:10)" },
    { question: "Nossa cidadania principal está...", options: ["Na terra", "Em nosso país", "Nos céus", "Em lugar nenhum"], correctAnswerIndex: 2, explanation: "Embora vivamos neste mundo, nossa verdadeira identidade e lealdade pertencem ao Reino dos Céus. Somos peregrinos aqui. (Filipenses 3:20)" },
    { question: "Somos chamados para ser...", options: ["Sal da terra e luz do mundo", "Escondidos e invisíveis", "Críticos e juízes", "Conformados com o mundo"], correctAnswerIndex: 0, explanation: "Jesus nos deu a missão de influenciar positivamente o mundo, preservando-o da corrupção (sal) e iluminando a escuridão (luz). (Mateus 5:13-16)" },
    { question: "Qual é a Grande Comissão dada por Jesus?", options: ["Construir grandes templos", "Ficar em casa e orar", "Ir e fazer discípulos de todas as nações", "Acumular conhecimento bíblico sem praticar"], correctAnswerIndex: 2, explanation: "A missão final que Jesus deixou para a Igreja é a de espalhar o evangelho e ensinar as nações a segui-lo. (Mateus 28:19-20)" },
    { question: "Seus dons e talentos foram dados por Deus para...", options: ["Seu próprio benefício", "Edificar a igreja e glorificar a Deus", "Se exibir", "Competir com os outros"], correctAnswerIndex: 1, explanation: "Cada cristão recebe dons espirituais para servir e fortalecer o corpo de Cristo, a Igreja, e para a glória de Deus. (1 Pedro 4:10)" },
  ]
};

export const getRandomQuestions = (stageId: number, count: number = 10): QuizQuestion[] => {
  const bank = allQuestions[stageId];
  if (!bank) return [];
  
  const shuffledBank = shuffleArray(bank);
  return shuffledBank.slice(0, count);
};