import { QuizQuestion } from './types';

// Helper function to shuffle an array
const shuffleArray = <T,>(array: T[]): T[] => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

const allQuestions: Record<number, QuizQuestion[]> = {
  1: [
    { question: "De acordo com Gênesis 1, à imagem de quem fomos criados?", options: ["Anjos", "Natureza", "Deus", "Estrelas"], correctAnswerIndex: 2, explanation: "Gênesis 1:27 afirma claramente: 'Deus criou o homem à sua imagem; à imagem de Deus o criou'. Isso nos dá valor e dignidade intrínsecos." },
    { question: "O que significa ser criado à imagem de Deus?", options: ["Ter superpoderes", "Refletir Seu caráter e amor", "Ser fisicamente igual a Ele", "Nunca cometer erros"], correctAnswerIndex: 1, explanation: "Ser imagem de Deus não é sobre aparência física, mas sobre refletir Seus atributos morais, espirituais e intelectuais, como amor, justiça e criatividade. (Efésios 5:1)" },
    { question: "Qual a importância de saber que você é imagem de Deus?", options: ["Isso nos torna superiores", "Não tem importância", "Define nosso valor e propósito", "É apenas um detalhe"], correctAnswerIndex: 2, explanation: "Entender que somos imagem de Deus estabelece nosso valor inerente. Não somos definidos por opiniões ou falhas, mas por nosso Criador. (Salmos 139:14)" },
    { question: "A criação do homem foi um ato...", options: ["Acidental", "Intencional e planejado", "Sem propósito", "Rápido e sem detalhes"], correctAnswerIndex: 1, explanation: "A narrativa da criação em Gênesis mostra Deus agindo com propósito e planejamento, culminando na criação da humanidade como o ápice de Sua obra. (Gênesis 1:26)" },
    { question: "Deus nos criou para termos...", options: ["Domínio sobre os outros", "Relacionamento com Ele", "Riqueza material", "Fama"], correctAnswerIndex: 1, explanation: "O propósito principal da nossa criação é ter um relacionamento íntimo com Deus. Fomos feitos para conhecê-Lo e amá-Lo. (João 17:3)" },
    { question: "Ser imagem de Deus nos dá...", options: ["Uma licença para pecar", "Responsabilidades", "Tristeza", "Imunidade a problemas"], correctAnswerIndex: 1, explanation: "Como portadores da imagem de Deus, temos a responsabilidade de cuidar da criação e de representar Seu caráter no mundo. (Gênesis 1:28)" },
    { question: "O que nos diferencia do resto da criação?", options: ["Nossa força física", "Nossa capacidade de voar", "Nossa alma e espírito", "Nossa velocidade"], correctAnswerIndex: 2, explanation: "A humanidade é única na criação por possuir um espírito, o que nos permite ter comunhão com Deus de uma forma que os animais não podem. (1 Tessalonicenses 5:23)" },
    { question: "Como podemos honrar a imagem de Deus em nós?", options: ["Ignorando os outros", "Amando a Deus e ao próximo", "Buscando apenas nossos interesses", "Criticando a todos"], correctAnswerIndex: 1, explanation: "O grande mandamento é amar a Deus e ao próximo. Ao fazermos isso, refletimos o caráter de Deus e honramos Sua imagem em nós. (Mateus 22:37-39)" },
    { question: "A Bíblia diz que fomos feitos de forma...", options: ["Assustadora e estranha", "Simples e comum", "Maravilhosa e admíravel", "Frágil e sem valor"], correctAnswerIndex: 2, explanation: "O Salmo 139:14 declara: 'Eu te louvarei, porque de um modo assombroso e tão maravilhoso fui feito'. Somos uma obra de arte de Deus." },
    { question: "Sua identidade começa ao entender que você é...", options: ["Uma obra do acaso", "Criação de Deus", "Definido por seus erros", "Definido pela opinião dos outros"], correctAnswerIndex: 1, explanation: "A base de toda identidade sólida é reconhecer que nossa existência não é um acidente, mas um ato de amor do Criador. (Efésios 2:10)" },
    { question: "A criação em Gênesis revela um Deus...", options: ["Distante", "Desorganizado", "Organizado e criativo", "Zangado"], correctAnswerIndex: 2, explanation: "A forma como Deus cria o mundo em Gênesis, separando luz e trevas, águas e terra, mostra um Deus de ordem e imensa criatividade. (Gênesis 1)" },
    { question: "Qual foi o 'sopro de vida' que Deus deu ao homem?", options: ["Vento", "Água", "Seu próprio fôlego/espírito", "Fogo"], correctAnswerIndex: 2, explanation: "Gênesis 2:7 diz que Deus 'soprou em suas narinas o fôlego da vida, e o homem se tornou um ser vivente'. Isso destaca uma conexão íntima e única com Deus." },
    { question: "Ser criado 'homem e mulher' à imagem de Deus reflete o que sobre Ele?", options: ["Que Deus é solitário", "A importância da comunidade e do relacionamento", "Que Deus tem gênero", "Não reflete nada"], correctAnswerIndex: 1, explanation: "A criação de dois gêneros complementares que formam uma unidade reflete a natureza relacional do Deus Triúno (Pai, Filho, Espírito Santo). (Gênesis 1:27)" },
    { question: "A ordem de Deus para 'dominar' a terra significa...", options: ["Destruir a natureza", "Cuidar e administrar a criação", "Ignorar os animais", "Explorar sem limites"], correctAnswerIndex: 1, explanation: "O 'domínio' aqui tem o sentido de mordomia, de um cuidado responsável e zeloso pela criação, como um bom administrador. (Gênesis 1:28)" },
    { question: "Qual atributo de Deus é refletido em nossa capacidade de criar (arte, música, etc)?", options: ["Sua justiça", "Sua criatividade", "Sua ira", "Sua santidade"], correctAnswerIndex: 1, explanation: "Como fomos feitos à imagem de um Deus criativo, também recebemos a capacidade de criar, inovar e apreciar a beleza. (Êxodo 35:31-33)" },
  ],
  2: [
    { question: "O que o pecado causou na relação do homem com Deus?", options: ["Aproximação", "Indiferença", "Separação", "Fortalecimento"], correctAnswerIndex: 2, explanation: "O pecado criou uma barreira espiritual entre a humanidade e um Deus santo, resultando em separação. (Isaías 59:2)" },
    { question: "Qual foi a consequência da desobediência de Adão e Eva?", options: ["Receberam um prêmio", "Foram expulsos do Éden", "Nada aconteceu", "Ganharam mais sabedoria"], correctAnswerIndex: 1, explanation: "A consequência direta da desobediência foi a expulsão do Jardim do Éden, perdendo a comunhão íntima com Deus. (Gênesis 3:23-24)" },
    { question: "Romanos 3:23 afirma que 'todos...'", options: ["São perfeitos", "Pecaram", "São anjos", "Não precisam de Deus"], correctAnswerIndex: 1, explanation: "Este versículo é fundamental para entender que a condição de pecador é universal, afetando toda a humanidade. Ninguém está isento. (Romanos 3:23)" },
    { question: "A identidade original do homem foi afetada pelo...?", options: ["Pecado", "Trabalho", "Descanso", "Louvor"], correctAnswerIndex: 0, explanation: "O pecado distorceu a imagem de Deus no homem, afetando sua identidade e propósito originais. (Romanos 5:12)" },
    { question: "O que significa estar 'destituído da glória de Deus'?", options: ["Estar mais perto de Deus", "Ter alcançado a perfeição", "Estar separado do padrão de Deus", "Ser mais glorioso que Deus"], correctAnswerIndex: 2, explanation: "Significa que, por causa do pecado, não conseguimos atingir o padrão perfeito e glorioso de Deus. Estamos aquém. (Romanos 3:23)" },
    { question: "Após a queda, o homem começou a sentir...", options: ["Paz e alegria", "Apenas amor", "Medo e vergonha", "Orgulho e superioridade"], correctAnswerIndex: 2, explanation: "A primeira reação de Adão e Eva após pecarem foi se esconderem de Deus, sentindo medo e vergonha de sua nudez. (Gênesis 3:10)" },
    { question: "A serpente no Éden representa...", options: ["Um amigo", "A sabedoria", "A tentação e o engano", "Um guia"], correctAnswerIndex: 2, explanation: "A serpente, identificada como Satanás, representa o engano e a tentação que nos leva a duvidar da bondade e da palavra de Deus. (Apocalipse 12:9)" },
    { question: "Qual a raiz do primeiro pecado?", options: ["Fome", "Cansaço", "Dúvida da palavra de Deus", "Amor"], correctAnswerIndex: 2, explanation: "A tentação começou quando Eva duvidou do que Deus havia ordenado, abrindo a porta para a desobediência. (Gênesis 3:1-6)" },
    { question: "Apesar da queda, Deus...", options: ["Abandonou a humanidade", "Desistiu de seu plano", "Prometeu um Redentor", "Castigou sem esperança"], correctAnswerIndex: 2, explanation: "Imediatamente após a queda, Deus prometeu um Salvador que esmagaria a cabeça da serpente, mostrando que Ele não havia desistido da humanidade. (Gênesis 3:15)" },
    { question: "Entender a queda nos ajuda a reconhecer nossa necessidade de um...", options: ["Salvador", "Amigo", "Líder", "Professor"], correctAnswerIndex: 0, explanation: "Ao compreendermos que estamos separados de Deus por nosso pecado, percebemos nossa incapacidade de nos salvar e nossa profunda necessidade de um Salvador. (Romanos 7:24-25)" },
    { question: "Qual foi a primeira reação de Adão ao ser confrontado por Deus?", options: ["Pediu perdão", "Ficou em silêncio", "Culpou Eva", "Culpou a si mesmo"], correctAnswerIndex: 2, explanation: "Em Gênesis 3:12, Adão tenta transferir a culpa, dizendo: 'A mulher que me deste por companheira, ela me deu da árvore, e eu comi'. Isso mostra como o pecado afeta nosso caráter." },
    { question: "O que o 'salário do pecado' resulta, segundo Romanos 6:23?", options: ["Riqueza", "Fama", "Morte", "Sabedoria"], correctAnswerIndex: 2, explanation: "Romanos 6:23 é claro: 'Pois o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor'. A morte aqui significa separação eterna de Deus." },
    { question: "O conhecimento do bem e do mal trouxe...", options: ["Paz interior", "Conflito e sofrimento", "Poderes divinos", "Felicidade plena"], correctAnswerIndex: 1, explanation: "Ao desobedecerem, a humanidade passou a conhecer o mal por experiência própria, o que introduziu dor, sofrimento, e conflito no mundo. (Gênesis 3:16-19)" },
    { question: "A terra foi amaldiçoada por causa da...", options: ["Chuva", "Desobediência do homem", "Falta de cuidado", "Vontade de Deus"], correctAnswerIndex: 1, explanation: "Em Gênesis 3:17, Deus diz a Adão: 'Maldita é a terra por sua causa'. Isso mostra que o pecado humano teve consequências cósmicas." },
    { question: "Por que Caim matou Abel?", options: ["Por um acidente", "Por inveja e ira", "Por uma disputa de terras", "Por ordem de seus pais"], correctAnswerIndex: 1, explanation: "Caim ficou irado porque a oferta de Abel foi aceita por Deus e a sua não. O pecado, quando não tratado, levou ao assassinato, mostrando sua progressão. (Gênesis 4:5-8)" },
  ],
  3: [
    { question: "Segundo 2 Coríntios 5:17, quem está em Cristo é...", options: ["A mesma pessoa", "Um pouco melhorado", "Nova criação", "Alguém sem memória"], correctAnswerIndex: 2, explanation: "A transformação em Cristo é radical. Não é uma reforma, mas uma recriação completa do nosso espírito. (2 Coríntios 5:17)" },
    { question: "O que acontece com as 'coisas antigas'?", options: ["Elas se fortalecem", "Elas já passaram", "Elas ficam escondidas", "Elas definem o futuro"], correctAnswerIndex: 1, explanation: "A nossa antiga vida de pecado, culpa e condenação é deixada para trás. Em Cristo, temos um novo começo. (2 Coríntios 5:17)" },
    { question: "Quem realiza essa transformação para 'nova criação'?", options: ["Nós mesmos, com esforço", "O Espírito Santo", "Nossos amigos", "O pastor da igreja"], correctAnswerIndex: 1, explanation: "O novo nascimento é uma obra sobrenatural do Espírito Santo em nós no momento em que cremos em Jesus. (Tito 3:5)" },
    { question: "O que significa ser 'nova criação'?", options: ["Mudar de nome", "Ter uma nova natureza espiritual", "Mudar de aparência física", "Esquecer todos os amigos"], correctAnswerIndex: 1, explanation: "Significa que recebemos uma nova natureza, com novos desejos que se alinham com a vontade de Deus. (Ezequiel 36:26)" },
    { question: "Essa nova identidade é baseada em...", options: ["Nossas obras", "Nossa família", "Nossa fé em Cristo", "Nossa popularidade"], correctAnswerIndex: 2, explanation: "Nossa identidade não vem do que fazemos, mas do que Cristo fez por nós. Ela é recebida pela fé. (Gálatas 2:20)" },
    { question: "Como recebemos essa nova vida?", options: ["Pagando por ela", "Por merecimento", "Pela graça, mediante a fé", "Trabalhando muito"], correctAnswerIndex: 2, explanation: "A salvação e a nova vida são um presente gratuito de Deus (graça), que recebemos através da fé, não por nossos próprios méritos. (Efésios 2:8-9)" },
    { question: "A vida antiga era marcada pelo pecado, a nova vida é marcada pela...", options: ["Justiça de Cristo", "Perfeição imediata", "Ausência de problemas", "Riqueza"], correctAnswerIndex: 0, explanation: "Quando estamos em Cristo, somos revestidos com a Sua justiça. Deus nos vê como justos por causa do sacrifício de Jesus. (2 Coríntios 5:21)" },
    { question: "O batismo simboliza...", options: ["Apenas um banho", "Morte para o pecado e ressurreição em Cristo", "Entrada em um clube", "Uma tradição sem significado"], correctAnswerIndex: 1, explanation: "O batismo é um símbolo externo da realidade interna de morrer para a velha vida de pecado e ressuscitar para uma nova vida em Cristo. (Romanos 6:4)" },
    { question: "Nossa nova identidade em Cristo é...", options: ["Temporária", "Frágil", "Eterna e segura", "Dependente do nosso humor"], correctAnswerIndex: 2, explanation: "Nossa posição em Cristo é segura e eterna, garantida pelo selo do Espírito Santo. (Efésios 1:13-14)" },
    { question: "Quando nos tornamos 'nova criação', começamos um processo de...", options: ["Acomodação", "Santificação", "Regressão", "Isolamento"], correctAnswerIndex: 1, explanation: "A santificação é o processo contínuo pelo qual o Espírito Santo nos molda para sermos cada vez mais parecidos com Jesus. (Filipenses 1:6)" },
    { question: "Em Gálatas 2:20, Paulo diz: 'Não sou mais eu quem vive, mas...'", options: ["'...o pastor vive em mim'", "'...Cristo vive em mim'", "'...a lei vive em mim'", "'...meus desejos vivem em mim'"], correctAnswerIndex: 1, explanation: "Este versículo resume a essência da nova identidade: nossa vida antiga foi crucificada com Cristo, e agora é Ele quem vive e age através de nós pela fé." },
    { question: "O que 'nascer de novo' significa, segundo Jesus em João 3?", options: ["Voltar ao ventre da mãe", "Um nascimento espiritual", "Mudar de cidade", "Começar a ler a Bíblia"], correctAnswerIndex: 1, explanation: "Jesus explica a Nicodemos que o novo nascimento não é físico, mas uma obra espiritual do Espírito Santo necessária para ver o Reino de Deus. (João 3:3-6)" },
    { question: "Ser uma nova criação nos dá um novo...", options: ["Corpo físico", "Círculo de amigos", "Propósito de vida", "Nome na certidão"], correctAnswerIndex: 2, explanation: "Antes vivíamos para nós mesmos, mas como nova criação, nosso propósito se alinha com o de Deus: glorificá-lo e viver para Ele. (1 Coríntios 10:31)" },
    { question: "Qual a evidência de que alguém é uma 'nova criação'?", options: ["Falar em línguas estranhas", "Ir à igreja todos os dias", "O fruto do Espírito em sua vida", "Saber toda a Bíblia de cor"], correctAnswerIndex: 2, explanation: "A evidência real de transformação é o caráter de Cristo sendo formado em nós, o que Gálatas 5:22-23 chama de 'fruto do Espírito' (amor, alegria, paz, etc.)." },
    { question: "A nossa mente também é renovada neste processo?", options: ["Não, ela permanece a mesma", "Sim, pela Palavra de Deus", "Apenas se fizermos terapia", "Não é importante"], correctAnswerIndex: 1, explanation: "Romanos 12:2 nos exorta a sermos transformados pela 'renovação da nossa mente', o que acontece quando meditamos e aplicamos a Palavra de Deus em nossa vida." },
  ],
  4: [
    { question: "Em Cristo, qual é a nossa nova posição?", options: ["Servos distantes", "Inimigos", "Filhos de Deus", "Conhecidos"], correctAnswerIndex: 2, explanation: "Através da fé em Jesus, somos adotados na família de Deus e nos tornamos Seus filhos. (Gálatas 4:4-5)" },
    { question: "Como somos chamados, segundo 1 João 3:1?", options: ["Pecadores", "Trabalhadores", "Filhos de Deus", "Meros mortais"], correctAnswerIndex: 2, explanation: "O apóstolo João se maravilha com o amor de Deus que nos concede o status de 'filhos de Deus'. (1 João 3:1)" },
    { question: "Essa filiação é resultado do quê?", options: ["Do nosso esforço", "Do grande amor de Deus", "Do acaso", "De uma compra"], correctAnswerIndex: 1, explanation: "Nossa adoção como filhos não é por nosso mérito, mas um ato do imenso amor e da soberana vontade de Deus. (Efésios 1:5)" },
    { question: "O Espírito Santo em nós clama...", options: ["'Socorro'", "'Aba, Pai'", "'Estou perdido'", "'Me ajude'"], correctAnswerIndex: 1, explanation: "'Aba' é uma palavra aramaica de intimidade, similar a 'Papai'. O Espírito nos dá a confiança de nos aproximarmos de Deus com essa intimidade. (Romanos 8:15)" },
    { question: "Ser filho de Deus significa que somos...", options: ["Co-herdeiros com Cristo", "Mais importantes que os anjos", "Imunes ao sofrimento", "Perfeitos"], correctAnswerIndex: 0, explanation: "Como filhos de Deus, compartilhamos da herança de Cristo. Tudo o que pertence a Ele, por direito, também nos é prometido. (Romanos 8:17)" },
    { question: "Um pai amoroso...", options: ["Abandona", "Corrige e cuida", "Ignora", "Apenas critica"], correctAnswerIndex: 1, explanation: "Assim como um bom pai terreno, Deus Pai nos disciplina e corrige por amor, para o nosso crescimento e bem. (Hebreus 12:6)" },
    { question: "Nossa relação com Deus passa a ser de...", options: ["Medo e distância", "Intimidade e confiança", "Formalidade e regras", "Troca de favores"], correctAnswerIndex: 1, explanation: "Não somos mais escravos do medo, mas filhos que podem se aproximar do Pai com confiança e amor. (Gálatas 4:6-7)" },
    { question: "Não somos mais escravos do medo, mas recebemos o Espírito de...", options: ["Adoção", "Confusão", "Crítica", "Dúvida"], correctAnswerIndex: 0, explanation: "Romanos 8:15 contrasta o espírito de escravidão, que leva ao medo, com o Espírito de adoção, que nos confirma como filhos." },
    { question: "Como filhos, temos acesso direto a Deus através da...", options: ["Oração", "Riqueza", "Fama", "Sorte"], correctAnswerIndex: 0, explanation: "Por causa de Jesus, o véu foi rasgado. Como filhos, podemos entrar na presença de Deus com ousadia através da oração. (Hebreus 4:16)" },
    { question: "Sua identidade de filho é...", options: ["Baseada em performance", "Inabalável em Cristo", "Dependente da aprovação dos outros", "Temporária"], correctAnswerIndex: 1, explanation: "Sua identidade como filho de Deus é segura e firmada em Cristo, não em suas ações ou na opinião alheia. (João 1:12)" },
    { question: "A quem João 1:12 diz que foi dado o poder de se tornarem filhos de Deus?", options: ["A todos os que nasceram", "Aos que creem no nome de Jesus", "Aos que seguem as regras", "Aos que são de uma nação específica"], correctAnswerIndex: 1, explanation: "O critério para se tornar filho de Deus não é nascimento, etnia ou obras, mas simplesmente crer em Jesus Cristo como Salvador." },
    { question: "Se somos filhos, então somos herdeiros de Deus. O que herdaremos?", options: ["Problemas", "Riquezas terrenas", "A vida eterna e as promessas de Deus", "Nada"], correctAnswerIndex: 2, explanation: "Nossa herança como filhos de Deus inclui a vida eterna, um relacionamento restaurado com Ele e todas as bênçãos espirituais prometidas em Cristo. (Efésios 1:3)" },
    { question: "O que a parábola do Filho Pródigo nos ensina sobre Deus Pai?", options: ["Que Ele é um Pai que pune com severidade", "Que Ele esquece de seus filhos", "Que Ele espera de braços abertos pelo nosso retorno", "Que Ele só aceita filhos perfeitos"], correctAnswerIndex: 2, explanation: "A parábola de Lucas 15 mostra um Pai que corre ao encontro do filho arrependido, com amor e compaixão, celebrando seu retorno. Essa é a imagem do nosso Deus." },
    { question: "Ser filho de Deus nos livra de uma identidade de...", options: ["Órfão", "Rei", "Anjo", "Celebridade"], correctAnswerIndex: 0, explanation: "Antes de Cristo, estávamos espiritualmente órfãos, sem Pai e sem lar. Em Cristo, somos acolhidos em uma família e ganhamos uma identidade segura de pertencimento." },
    { question: "Como podemos viver como filhos amados no dia a dia?", options: ["Fazendo tudo o que queremos", "Ignorando as outras pessoas", "Obedecendo a Deus por amor, não por medo", "Tentando comprar o favor de Deus"], correctAnswerIndex: 2, explanation: "A resposta de um filho amado não é a rebeldia, mas uma obediência que brota da gratidão e do amor, confiando que os caminhos do Pai são os melhores. (1 João 5:3)" },
  ],
  5: [
    { question: "Para quem 'não há condenação'?", options: ["Para todos, sem exceção", "Para os que são perfeitos", "Para os que estão em Cristo Jesus", "Para ninguém"], correctAnswerIndex: 2, explanation: "Romanos 8:1 especifica que a ausência de condenação é para aqueles que estão unidos a Cristo pela fé." },
    { question: "O que nos liberta da lei do pecado e da morte?", options: ["Nossa própria força", "A lei do Espírito de vida em Cristo", "Regras religiosas", "Dinheiro"], correctAnswerIndex: 1, explanation: "Em Cristo, uma nova lei, a do Espírito, nos liberta do ciclo de pecado e morte que nos escravizava. (Romanos 8:2)" },
    { question: "Quem nos acusa, segundo a Bíblia?", options: ["Deus", "Jesus", "O Espírito Santo", "Satanás"], correctAnswerIndex: 3, explanation: "Apocalipse 12:10 chama Satanás de 'o acusador de nossos irmãos', que nos acusa diante de Deus dia e noite." },
    { question: "Jesus veio para...", options: ["Condenar o mundo", "Salvar o mundo", "Observar o mundo", "Ignorar o mundo"], correctAnswerIndex: 1, explanation: "Jesus mesmo declarou que Sua missão não era condenar, mas oferecer salvação a todos que cressem. (João 3:17)" },
    { question: "Se confessarmos os nossos pecados, Ele é fiel e justo para...", options: ["Nos punir severamente", "Nos perdoar e purificar", "Nos lembrar deles sempre", "Contar para todos"], correctAnswerIndex: 1, explanation: "A promessa de Deus é que a confissão sincera leva ao perdão completo e à purificação de toda injustiça. (1 João 1:9)" },
    { question: "A liberdade em Cristo nos dá o direito de...", options: ["Continuar pecando", "Viver para agradar a Deus", "Julgar os outros", "Fazer o que quisermos sem consequências"], correctAnswerIndex: 1, explanation: "Fomos libertados do pecado não para voltarmos a ele, mas para vivermos em novidade de vida, servindo a Deus. (Gálatas 5:13)" },
    { question: "O perdão de Deus é...", options: ["Parcial", "Completo", "Temporário", "Limitado"], correctAnswerIndex: 1, explanation: "Quando Deus perdoa, Ele lança nossos pecados 'nas profundezas do mar' e não se lembra mais deles. É um perdão total. (Miquéias 7:19)" },
    { question: "A verdadeira liberdade não é ausência de regras, mas...", options: ["Viver alinhado com a vontade de Deus", "Fazer tudo que se tem vontade", "Criar suas próprias regras", "Viver sem propósito"], correctAnswerIndex: 0, explanation: "A liberdade bíblica não é anarquia. É ser livre do poder do pecado para poder viver de acordo com o propósito para o qual fomos criados. (João 8:36)" },
    { question: "Quando a culpa tentar te acusar, você deve lembrar-se...", options: ["De todos os seus erros", "Da opinião dos outros", "Do sacrifício de Cristo", "De como você é fraco"], correctAnswerIndex: 2, explanation: "A base da nossa justificação não são nossos sentimentos ou obras, mas o fato consumado do sacrifício de Cristo na cruz. (Romanos 8:33-34)" },
    { question: "Andar no Espírito significa...", options: ["Flutuar", "Ser guiado e fortalecido por Ele", "Ignorar o mundo real", "Ser perfeito"], correctAnswerIndex: 1, explanation: "Andar no Espírito é viver o dia a dia em submissão e dependência do Espírito Santo, permitindo que Ele guie nossas decisões e atitudes. (Gálatas 5:16)" },
    { question: "'Conhecereis a verdade, e a verdade vos...'", options: ["...libertará'", "...aprisionará'", "...confundirá'", "...enriquecerá'"], correctAnswerIndex: 0, explanation: "Em João 8:32, Jesus afirma que o conhecimento da verdade (Ele mesmo e Sua Palavra) é o que nos liberta da escravidão do pecado e do engano." },
    { question: "O que o sangue de Jesus faz por nós?", options: ["Nos torna ricos", "Nos purifica de todo pecado", "Nos dá força física", "Nos torna famosos"], correctAnswerIndex: 1, explanation: "1 João 1:7 diz que 'o sangue de Jesus, seu Filho, nos purifica de todo pecado'. É o fundamento do nosso perdão e liberdade." },
    { question: "Quem pagou o preço pela nossa liberdade?", options: ["Nós mesmos, com boas obras", "Nossos pais", "Jesus Cristo, na cruz", "Ninguém pagou"], correctAnswerIndex: 2, explanation: "Fomos 'comprados por um bom preço'. O sacrifício de Cristo foi o pagamento que quitou a dívida do nosso pecado, nos libertando da escravidão. (1 Coríntios 6:20)" },
    { question: "Como devemos usar nossa liberdade em Cristo?", options: ["Para servir uns aos outros em amor", "Para fazer o mal escondido", "Para nos isolar do mundo", "Para buscar nossos próprios interesses"], correctAnswerIndex: 0, explanation: "Gálatas 5:13 nos adverte a não usar a liberdade como uma oportunidade para a carne, mas sim para servir ao próximo com amor." },
    { question: "A justificação pela fé significa que somos declarados...", options: ["Culpados", "Inocentes/Justos", "Em observação", "Melhores que os outros"], correctAnswerIndex: 1, explanation: "Justificar é um termo legal que significa 'declarar justo'. Pela fé em Cristo, Deus nos declara justos, não por nossos méritos, mas pelos méritos de Cristo. (Romanos 5:1)" },
  ],
  6: [
    { question: "Em Efésios 2:10, somos chamados de...", options: ["'Acidentes cósmicos'", "'Feitura de Deus'", "'Seres sem importância'", "'Projeto inacabado'"], correctAnswerIndex: 1, explanation: "A palavra grega para 'feitura' é 'poiema', de onde vem 'poema'. Somos a obra-prima, o poema de Deus. (Efésios 2:10)" },
    { question: "Fomos criados em Cristo para...", options: ["As boas obras", "Vivermos para nós mesmos", "Acumular riquezas", "Apenas descansar"], correctAnswerIndex: 0, explanation: "Nossa salvação não é *pelas* obras, mas *para* as obras. Elas são a evidência da nossa nova vida em Cristo. (Efésios 2:10)" },
    { question: "Essas boas obras foram preparadas...", options: ["Por nós mesmos", "De improviso", "De antemão por Deus", "Pela sociedade"], correctAnswerIndex: 2, explanation: "Deus, em Sua soberania, já planejou as obras que Ele quer que realizemos. Nosso papel é andar nesse caminho que Ele preparou. (Efésios 2:10)" },
    { question: "Nossa cidadania principal está...", options: ["Na terra", "Em nosso país", "Nos céus", "Em lugar nenhum"], correctAnswerIndex: 2, explanation: "Embora vivamos neste mundo, nossa verdadeira identidade e lealdade pertencem ao Reino dos Céus. Somos peregrinos aqui. (Filipenses 3:20)" },
    { question: "Somos chamados para ser...", options: ["Sal da terra e luz do mundo", "Escondidos e invisíveis", "Críticos e juízes", "Conformados com o mundo"], correctAnswerIndex: 0, explanation: "Jesus nos deu a missão de influenciar positivamente o mundo, preservando-o da corrupção (sal) e iluminando a escuridão (luz). (Mateus 5:13-16)" },
    { question: "Qual é a Grande Comissão dada por Jesus?", options: ["Construir grandes templos", "Ficar em casa e orar", "Ir e fazer discípulos de todas as nações", "Acumular conhecimento bíblico sem praticar"], correctAnswerIndex: 2, explanation: "A missão final que Jesus deixou para a Igreja é a de espalhar o evangelho e ensinar as nações a segui-lo. (Mateus 28:19-20)" },
    { question: "Viver com propósito significa...", options: ["Estar sempre ocupado", "Entender que sua vida serve a um plano maior de Deus", "Ter um emprego famoso", "Ser popular"], correctAnswerIndex: 1, explanation: "O verdadeiro propósito é encontrado quando alinhamos nossa vida ao plano de Deus, entendendo que somos parte de Sua grande história. (Romanos 8:28)" },
    { question: "Seus dons e talentos foram dados por Deus para...", options: ["Seu próprio benefício", "Edificar a igreja e glorificar a Deus", "Se exibir", "Competir com os outros"], correctAnswerIndex: 1, explanation: "Cada cristão recebe dons espirituais para servir e fortalecer o corpo de Cristo, a Igreja, e para a glória de Deus. (1 Pedro 4:10)" },
    { question: "Como 'embaixadores de Cristo', nossa missão é...", options: ["Representar a nós mesmos", "Representar Cristo e seu Reino", "Representar nosso país", "Representar nossa igreja"], correctAnswerIndex: 1, explanation: "Um embaixador representa oficialmente seu rei e seu reino em terra estrangeira. Nós representamos Cristo para o mundo. (2 Coríntios 5:20)" },
    { question: "Sua identidade em Cristo te dá um...", options: ["Fardo pesado", "Motivo para se orgulhar", "Propósito eterno", "Passado de acusações"], correctAnswerIndex: 2, explanation: "Sua nova identidade não é apenas sobre o passado (perdão), mas sobre o futuro: um propósito eterno que transcende esta vida. (Efésios 1:11-12)" },
    { question: "O que significa glorificar a Deus?", options: ["Cantar bem alto", "Viver de uma maneira que mostre o quão grande Ele é", "Dar muito dinheiro para a igreja", "Ser famoso"], correctAnswerIndex: 1, explanation: "Glorificar a Deus é refletir Seu caráter em nossas ações, palavras e atitudes, de modo que outras pessoas vejam a bondade dEle através de nós. (Mateus 5:16)" },
    { question: "Ser 'sal da terra' implica em...", options: ["Ser uma pessoa amarga", "Preservar o mundo da corrupção moral e espiritual", "Ter uma dieta saudável", "Ficar isolado"], correctAnswerIndex: 1, explanation: "O sal na antiguidade era usado para preservar. Como sal, os cristãos devem atuar como um agente de preservação moral e espiritual na sociedade. (Mateus 5:13)" },
    { question: "Ser 'luz do mundo' significa...", options: ["Usar roupas brilhantes", "Revelar a verdade e a bondade de Deus em um mundo escuro", "Falar muito alto", "Estar sempre em evidência"], correctAnswerIndex: 1, explanation: "A luz expõe as trevas e guia o caminho. Devemos viver de tal forma que nossa vida aponte para a verdade e a esperança encontradas em Deus. (Mateus 5:14-16)" },
    { question: "Deus nos equipa para as boas obras através do...", options: ["Nosso próprio esforço", "Dinheiro", "Espírito Santo e Seus dons", "Nossa inteligência"], correctAnswerIndex: 2, explanation: "É o Espírito Santo quem nos capacita e nos dá dons espirituais para que possamos cumprir as obras que Deus preparou para nós. (1 Coríntios 12:7)" },
    { question: "Nosso propósito final, segundo o Catecismo de Westminster, é...", options: ["Ser feliz a qualquer custo", "Glorificar a Deus e gozá-lo para sempre", "Acumular bens", "Deixar um legado de fama"], correctAnswerIndex: 1, explanation: "Esta famosa declaração resume o propósito da vida humana: nossa existência encontra seu significado máximo em um relacionamento de adoração e alegria com nosso Criador." },
  ]
};

export const getRandomQuestions = (stageId: number, count: number = 10): QuizQuestion[] => {
  const bank = allQuestions[stageId];
  if (!bank) return [];
  
  const shuffledBank = shuffleArray(bank);
  return shuffledBank.slice(0, count);
};
